Traceback (most recent call last):
  File "manage.py", line 14, in <module>
    execute_manager(settings)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 438, in execute_manager
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 379, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 191, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 220, in execute
    output = self.handle(*args, **options)
  File "/home/moreno/projects/django/twitnerario/../twitnerario/apps/cronjobs/management/commands/cron.py", line 64, in handle
    registered[script](*args)
  File "/home/moreno/projects/django/twitnerario/../twitnerario/apps/core/tweet.py", line 71, in send_tweets
    api.PostUpdate(h+':'+m+tweet)
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Fri Nov 11 21:45:02 BRST 2011
Fri Nov 11 22:00:01 BRST 2011
Fri Nov 11 22:15:01 BRST 2011
[<Registros: @morenocunha>, <Registros: @morenocunha>]
Traceback (most recent call last):
  File "manage.py", line 14, in <module>
    execute_manager(settings)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 438, in execute_manager
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 379, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 191, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 220, in execute
    output = self.handle(*args, **options)
  File "/home/moreno/projects/django/twitnerario/../twitnerario/apps/cronjobs/management/commands/cron.py", line 64, in handle
    registered[script](*args)
  File "/home/moreno/projects/django/twitnerario/../twitnerario/apps/core/tweet.py", line 72, in send_tweets
    api.PostUpdate(str(h)+':'+str(m)+tweet)
  File "/usr/local/lib/python2.7/dist-packages/python_twitter-0.8.2-py2.7.egg/twitter.py", line 2766, in PostUpdate
    data = self._ParseAndCheckTwitter(json)
  File "/usr/local/lib/python2.7/dist-packages/python_twitter-0.8.2-py2.7.egg/twitter.py", line 3668, in _ParseAndCheckTwitter
    self._CheckForTwitterError(data)
  File "/usr/local/lib/python2.7/dist-packages/python_twitter-0.8.2-py2.7.egg/twitter.py", line 3691, in _CheckForTwitterError
    raise TwitterError(data['error'])
twitter.TwitterError: Status is a duplicate.
Fri Nov 11 22:30:01 BRST 2011
[<Registros: @morenocunha>]
Fri Nov 11 22:45:01 BRST 2011
Fri Nov 11 23:00:01 BRST 2011
Fri Nov 11 23:15:01 BRST 2011
Fri Nov 11 23:30:01 BRST 2011
Fri Nov 11 23:45:01 BRST 2011
Sat Nov 12 00:00:01 BRST 2011
Sat Nov 12 00:15:01 BRST 2011
Sat Nov 12 00:30:01 BRST 2011
Sat Nov 12 00:45:01 BRST 2011
Sat Nov 12 01:00:01 BRST 2011
Sat Nov 12 01:15:01 BRST 2011
Sat Nov 12 01:30:01 BRST 2011
Sat Nov 12 01:45:01 BRST 2011
Sat Nov 12 02:00:01 BRST 2011
Sat Nov 12 11:00:01 BRST 2011
Sat Nov 12 11:15:01 BRST 2011
Sat Nov 12 11:30:01 BRST 2011
Sat Nov 12 11:45:01 BRST 2011
Sat Nov 12 12:00:01 BRST 2011
Sat Nov 12 12:15:01 BRST 2011
Sat Nov 12 12:30:01 BRST 2011
Sat Nov 12 12:45:01 BRST 2011
Sat Nov 12 13:00:01 BRST 2011
Sat Nov 12 13:15:01 BRST 2011
Sat Nov 12 23:00:01 BRST 2011
Sat Nov 12 23:15:01 BRST 2011
Sat Nov 12 23:30:01 BRST 2011
Sat Nov 12 23:45:01 BRST 2011
Sun Nov 13 00:00:01 BRST 2011
Sun Nov 13 00:15:01 BRST 2011
Sun Nov 13 00:30:01 BRST 2011
Sun Nov 13 12:15:01 BRST 2011
Sun Nov 13 12:30:01 BRST 2011
Sun Nov 13 12:45:01 BRST 2011
Sun Nov 13 13:00:01 BRST 2011
Sun Nov 13 13:15:02 BRST 2011
Sun Nov 13 13:30:01 BRST 2011
Sun Nov 13 13:45:01 BRST 2011
Sun Nov 13 14:00:01 BRST 2011
Sun Nov 13 14:15:01 BRST 2011
Sun Nov 13 14:30:01 BRST 2011
Sun Nov 13 14:45:01 BRST 2011
Sun Nov 13 15:00:01 BRST 2011
Sun Nov 13 15:15:01 BRST 2011
Sun Nov 13 15:30:01 BRST 2011
Sun Nov 13 15:45:01 BRST 2011
Sun Nov 13 16:00:01 BRST 2011
Sun Nov 13 16:15:01 BRST 2011
Sun Nov 13 19:30:01 BRST 2011
Sun Nov 13 19:45:01 BRST 2011
Sun Nov 13 20:00:01 BRST 2011
Sun Nov 13 20:15:01 BRST 2011
Sun Nov 13 20:30:01 BRST 2011
Sun Nov 13 20:45:01 BRST 2011
Sun Nov 13 21:00:01 BRST 2011
Sun Nov 13 21:15:01 BRST 2011
Traceback (most recent call last):
  File "manage.py", line 14, in <module>
    execute_manager(settings)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 438, in execute_manager
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 379, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 191, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 220, in execute
    output = self.handle(*args, **options)
  File "/home/moreno/projects/django/twitnerario/../twitnerario/apps/cronjobs/management/commands/cron.py", line 64, in handle
    registered[script](*args)
  File "/home/moreno/projects/django/twitnerario/../twitnerario/apps/core/tweet.py", line 99, in send_tweets
    api.PostUpdate(str(h)+':'+str(m)+' '+tweet)
  File "/usr/local/lib/python2.7/dist-packages/python_twitter-0.8.2-py2.7.egg/twitter.py", line 2766, in PostUpdate
    data = self._ParseAndCheckTwitter(json)
  File "/usr/local/lib/python2.7/dist-packages/python_twitter-0.8.2-py2.7.egg/twitter.py", line 3671, in _ParseAndCheckTwitter
    raise TwitterError("Capacity Error")
twitter.TwitterError: Capacity Error
Sun Nov 13 21:30:01 BRST 2011
Sun Nov 13 21:45:01 BRST 2011
Traceback (most recent call last):
  File "manage.py", line 14, in <module>
    execute_manager(settings)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 438, in execute_manager
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 379, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 191, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 220, in execute
    output = self.handle(*args, **options)
  File "/home/moreno/projects/django/twitnerario/../twitnerario/apps/cronjobs/management/commands/cron.py", line 64, in handle
    registered[script](*args)
  File "/home/moreno/projects/django/twitnerario/../twitnerario/apps/core/tweet.py", line 99, in send_tweets
    api.PostUpdate(str(h)+':'+str(m)+' '+tweet)
  File "/usr/local/lib/python2.7/dist-packages/python_twitter-0.8.2-py2.7.egg/twitter.py", line 2766, in PostUpdate
    data = self._ParseAndCheckTwitter(json)
  File "/usr/local/lib/python2.7/dist-packages/python_twitter-0.8.2-py2.7.egg/twitter.py", line 3668, in _ParseAndCheckTwitter
    self._CheckForTwitterError(data)
  File "/usr/local/lib/python2.7/dist-packages/python_twitter-0.8.2-py2.7.egg/twitter.py", line 3691, in _CheckForTwitterError
    raise TwitterError(data['error'])
twitter.TwitterError: Status is a duplicate.
Sun Nov 13 22:00:01 BRST 2011
